# catalog configuration
catalogs:
  # number of master catalogs
  elementCount: 1
  coverage: 1
  initialSeed: 12

  outputDir: "catalogs"
  outputFilePattern: "catalog_1.xml"

  # number of categories per catalog
  categories:
    elementCount: 50
    categoryTreeDepth: 7
    categoryTreeBreadth: 5

  # define category custom attributes
  customAttributes:
    enableCompare:
      type: boolean
      data: static
      staticValue: true
    showInMenu:
      type: boolean
      data: static
      staticValue: true
    headerMenuBanner:
      type: string
      data: static
      staticValue: ""
    string1:
      type: string
      data: random
      staticValue: ""
      searchable: true
    string2:
      type: string
      data: random
      staticValue: ""
      searchable: true
    date1:
      type: date
      data: random
      staticValue: ""
      searchable: false
    # This attribute, unlike others, is not used by SiteGenesis but to show the "searchable" config
    inStock:
      type: boolean
      data: random
      # Ignored, needed for bug #114 in jackson-kotlin
      staticValue: ""
      # This attribute will be indexed
      searchable: true

  # randomly generate category custom attributes
  #generatedAttributes:
    #elementCount: 5
    # out of 40 attributes, the first 10 will be indexed (and thus searchable)
    #thereofSearchable: 3

  # define shared variation attributes by name and available values
  sharedVariationAttributes:
    - name: "bindingType"
      values:
        - "Paperback"
        - "Hardcover"
        - "Audiobook"
        - "Board Book"
        - "Mass Market Paperback"
        - "Picture Book"
      probability: 0.49
      # shared attributes may include a probability factor as well, see below.
      # It's applied to all product definitions in which it is shared.
    #- name: "size"
     # values:
      #  - "1"
       # - "2"
      #probability: 0.7

  # configure shared product options
  #sharedOptions:
    # number of generated shared product options per catalog
    #elementCount: 10
    # minimum number of values per option
    #minValues: 1
    # maximum number of values per option
   # maxValues: 5
    # minimum price of product option value in USD
    #minPrice: 0.01
    # maximum price of product option value in USD
   # maxPrice: 500.0
    # Chance of a product using will use options. Results in about (not exactly) 10% of all products having them.
    #probability: 0.1

  products:
    # number of standard products per catalog
    elementCount: 1000
    #generatedAttributes:
      #elementCount: 5
      #thereofSearchable: 5

    customAttributes:
      adultOnly:
        type: boolean
        data: random
        staticValue: ""
        searchable: false
      canadian:
        type: boolean
        data: random
        staticValue: ""
        searchable: false
      isLargePrint:
        type: boolean
        data: random
        staticValue: ""
        searchable: false
      isMapApplicable:
        type: boolean
        data: random
        staticValue: ""
        searchable: false
      releaseDate:
        type: date
        data: random
        staticValue: ""
        searchable: false
      pageCount:
        type: integer
        data: random
        staticValue: ""
      id:
        type: string
        data: random
        staticValue: ""
        searchable: true
      isbn10:
        type: string
        data: random
        staticValue: ""
        searchable: true
      isbn13:
        type: string
        data: random
        staticValue: ""
        searchable: true
      layoutModuleID:
        type: string
        data: random
        staticValue: ""
        searchable: false
      merchCategoryID:
        type: string
        data: random
        staticValue: ""
        searchable: false
      shippingDepth:
        type: integer
        data: random
        staticValue: ""
        searchable: false
      shippingHeight:
        type: integer
        data: random
        staticValue: ""
        searchable: false
      shippingWidth:
        type: integer
        data: random
        staticValue: ""
        searchable: false
      shippingWeight:
        type: integer
        data: random
        staticValue: ""
        searchable: false
      combinedAttributes:
        type: string
        data: random
        staticValue: ""
        searchable: false
    #generatedAttributes:
      #elementCount: 10
      #thereofSearchable: 3
    localizableCustomAttributes:
      age:
        type: string
        data: list
        list: [ "Adult","Teen","Tween", "Kid","Toddler" ]
        searchable: false
        probability: 1
      contAuthor:
        type: string
        data: static
        staticValue: "Author"
        searchable: true
      title:
        type: string
        data: random
        staticValue: ""
        searchable: true
      language:
        type: string
        data: list
        list: [ "English","German","French", "Spanish","Others" ]
        searchable: false
      ContEditor:
        type: string
        data: random
        staticValue: ""
        searchable: false
      ContTranslator:
        type: string
        data: random
        staticValue: ""
        searchable: false
      ContIllustrator:
        type: string
        data: random
        staticValue: ""
        searchable: false


    # local options are defined _for each_ product individually. Since that's an uncommon (and expensive to generate)
    # use case, the default is to not have them.
    # The attributes supported are the same as for sharedOptions above
    #options:
    #  # The number of options _per product_. This combines with the number of products to give the total number of different options.
    #  elementCount: 0
    #  minValues: 1
    #  maxValues: 5
    #  minPrice: 0.01
    #  maxPrice: 500.0
    #  probability: 0.05

  variationProducts:
    # list of different variation master product configs
      # number of master products to generate per configuration
    - elementCount: 1
      # define local variation attributes
      localVariationAttributes:
        - name: "color"
          values:
            - "yellow"
            - "purple"
          # the probability default is "1.0f", that is, include every attribute value
          probability: 1.0
        - name: "memory-size"
          values:
            - "4 GB"
            - "8 GB"
            - "16 GB"
            - "32 GB"
          # a float from [0,1] - describes the probability of each value being selected for a given master product
          # NOTE: A probability of 0.5 DOES NOT guarantee inclusion of exactly half the attributes
          probability: 0.5
      # reference shared variation attributes to use
      sharedVariationAttributes:
        - "size"
    - elementCount: 1
      sharedVariationAttributes:
        - "bindingType"
        #- "size"

  #bundleConfig:
    # number of product bundles to generate
    #elementCount: 1

    # define range of bundled products per bundle
    #minBundledProducts: 2
    #maxBundledProducts: 5

 # productSets:
    # number of product sets to generate
    #elementCount: 1

    # define range of products per product set
    #minSetProducts: 3
    #maxSetProducts: 8

